name: Run Checks with Danger
on:
  issues:
    types: [milestoned, demilestoned]
  pull_request:
    # Because we have a rule that validates the PR labels, we want it to run
    # when the labels change, not only when a PR is opened/reopened or changes
    # are pushed to it.
    types: [opened, reopened, synchronize, labeled, unlabeled]

jobs:
  danger:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Till https://github.com/danger/danger-js/issues/1042 is fixed, we need
      # this workaround
      DANGER_GITHUB_API_BASE_URL: "https://api.github.com"
    if:
      # One of the Danger checks we run on PRs is for milestones, but the event
      # that triggers it is for issues. PRs are special issues but, unlike
      # labels, don't have a dedicated milestone event.   In order to run this
      # workflow only for PRs, we need to check the context to see if this was
      # triggered by a PR or a plain issue.
      github.event.pull_request != null || github.event.issue.pull_request != null
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node_version: 10.x

      - name: Install Yarn
        run: npm install -g yarn

      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-node_modules

      - name: Yarn Install
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        # frozen-lockfile will make the build fail if the lockfile is not there
        run: yarn install --frozen-lockfile

      - name: Danger
        run: |
          yarn run danger ci \
            --dangerfile Automattic/danger-settings/wordpress/ios.ts
