name: ☢️ Danger

on:
  pull_request:
    types: [opened, synchronize, edited, review_requested, review_request_removed, labeled, unlabeled, milestoned, demilestoned]

jobs:
  dangermattic:
    uses: Automattic/dangermattic/.github/workflows/reusable-run-danger.yml@v1.0.0
    secrets:
      github-token: ${{ secrets.DANGERMATTIC_GITHUB_TOKEN }}
